### ISSUE TITLE
My Game Gets Unpublished By Itself

### ISSUE THREAD

**Issue by Crafterz125** [moddio/taro#57]
I don't if this is normal but,my game gets unpublished after a day.I don't know if this is from the server or my scripts but,please fix this.I was trying to play with my friend.

**Comment by VietnamNeko** [comment]
would be nice if you could provide game link

**Comment by Crafterz125** [comment]
After a day this game gets unpublished.
https://beta.modd.io/play/2Nn6ljukv

**Comment by Crafterz125** [comment]
I think it's something with the scripts

**Comment by VietnamNeko** [comment]
if your game is empty for 10m it will get unpublished by itself

**Comment by Crafterz125** [comment]
thats why its unpublishing
im closing this now :)
