### ISSUE TITLE
Sanitized chat disabled?

### ISSUE THREAD

**Issue by catholicatheist** [moddio/taro#87]
It seems the censor for swearing has been completely disabled, and any word someone types will be seen for what it is rather than perhaps being substituted for asterisks, or *. Is this intentional? I'd attach an image of some of the cussing I've seen as proof, only I fear it would be inappropriate to even show. If you're curious as to what some people are saying, I'd recommend just going through the modd.io games and looking for a degenerate racist/sexist/antisemite, etc., as there are unfortunately many of them, much to the disadvantage of all the other good people who are just trying to play a fun game.

**Comment by DamienVesper** [comment]
The chat sanitizer, `bad-words`, was temporarily disabled in [0eabd1d](https://github.com/moddio/taro/commit/7b92b7820d1b764baa4d0063a6ed78f9c2eaba9c) due to server crashes on production. This will only last as long as the issue has not been resolved, and is not a permanent change.

**Comment by m0dE** [comment]
fixed
